name: Test Coverage Comment
on:
  pull_request:
    branches: [ main ]
    
jobs:
  coverage_comment:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: |
          npx jest --coverage --coverageReporters json-summary | tee ./coverage.txt

      - name: Jest coverage comment
        id: coverageComment
        uses: MishaKav/jest-coverage-comment@main
        with:
          titie: Test Coverage Report
          summary-title: Summary
          coverage-title: coverage datail
          badge-title: coverage
          coverage-path: ./coverage.txt
